name: R CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Use a Docker container with pre-installed R packages to speed up setup time
    container:
      image: rocker/tidyverse:4.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache R packages to avoid reinstalling them every run
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.R/library
          key: ${{ runner.os }}-R-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-R-

      # Set up and install R environment and required packages
      - name: Install additional R packages
        run: |
          Rscript -e 'install.packages(c("testthat", "shiny"), repos = "https://cloud.r-project.org")'

      # Run the tests using testthat
      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests")'
