name: R CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("caret", "e1071", "tidyverse", "testthat", "shiny"))'

      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests")'
