name: R CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Use a Docker container with a specific R version
    container:
      image: rocker/tidyverse:4.3.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up R using the specified version
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      # Cache R packages
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.R/library
          key: ${{ runner.os }}-R-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-R-

      # Install dependencies explicitly using remotes::install_cran()
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("remotes", repos="https://cloud.r-project.org")'
          Rscript -e 'remotes::install_cran(c("caret", "e1071", "tidyverse", "testthat", "shiny"), repos="https://cloud.r-project.org")'

      # Run tests
      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests")'
